### ISSUE TITLE
Escrever sobre Cloud

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/manual-arquiteto-moderno#10]
- [x]  IaaS, PaaS e o SaaS e os riscos de implantação
- [x] O que é de fato uma aplicação cloud-native
- [x] Kubernetes - Quando usar e quando não usar
- [ ] Service Mesh
	- [ ] Arquitetura
	- [ ] Orquestração
	- [ ] Ferramentas
- [ ] Serviços e riscos na implantação

**Comment by otaviojava** [comment]
@kmacedovarela eu tenho um material sobre `Serviços e riscos na implantação` que acho que vale a pena. Mandarei o material para ver o que vc acha, blz?

**Comment by kmacedovarela** [comment]
Thx pela contribuição Otávio.
