### ISSUE TITLE
escrever sobre A importância de aprender os conceitos ao invés de novos frameworks

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/manual-arquiteto-moderno#11]

**Comment by professorisidro** [comment]
done! @otaviojava @kmacedovarela eu sobrescrevi o que estava no chap 8 (pq depois quero ler com calma o que o Otavio escreveu para ver se faço um MERGE das 2 coisas bele?)

**Comment by otaviojava** [comment]
opa, blz

**Comment by kmacedovarela** [comment]
Excelente capítulo @professorisidro . Adorei. Por mim podemos passar para review pela editora.
 
@otaviojava mais algo a adicionar?

**Comment by kmacedovarela** [comment]
Ah, faltou uma coisa. @otaviojava , seria válido adicionar esse tópico lá? Acho que você sabe bastante sobre né?
// Teorema do CAP e seus impactos na arquitetura

**Comment by otaviojava** [comment]
Teorema do CAP, deixa para NoSQL
