### ISSUE TITLE
Ter relação capítulo Author

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/manual-arquiteto-moderno#17]
Esse é um material realizado em parceria com o a @thecodenation 

O público alvo  é para pleno e sênior, assim não precisa se preocupar com os conceitos básicos.
A ideia é falar os conceitos além do básico, por exemplo, caso você queria falar com o seu colego pleno e sênior o que você falaria?

O prazo para entrega dos capítulos é para o dia **10 de junho**.

| Chapter      | Author |
| ------------- | -----:|
|1 Domain Driven Design (DDD)| Maurício Salatino @salaboy  |
|2 Clean Code|Otavio Santana @otaviojava |
|3 Clean Architecture| Otavio Santana @otaviojava|
|4 Refatoração| @rponte |
|5 Microservices|Sergio Lopes @sergiolopessp |
|6 Banco de dados|Leandro Domingues e Jhonathan @jhomarolo |
|7 Cloud|Karina @kmacedovarela |
|8 A importância de aprender os conceitos ao invés de novos frameworks|@professorisidro|
|9 Precisamos falar sobre atualizações| Elder Moraes @eldermoraes|
|10 Destrinchando performance de aplicações| @sandrogiacom|

**Comment by sergiolopessp** [comment]
Separei alguns assuntos fora do Assunto de Micro-serviços, até porque fiquei na dúvida se eles deveriam estar em micro-serviços ou não. @otaviojava Dto ou não DTO, acho que tem mais haver com conceitos do que com Microservices, mas podemos discutir. @professorisidro Teorema de Cap e melhores praticas, fico na dúvida se é ali tambem, ou será que é micro-serviços mesmo. E paginação eu fico na dúvida, porque é banco de dados, mas poderia ser Microserviços. O que acham?

**Comment by otaviojava** [comment]
@sergiolopessp é uma boa conversa. Eu pensei "DTO ou não" em micro-serviços uma vez que dos capítulos é onde o DTO é mais falado ultimamente...
o Teorema do CAP, acho uma boa dar dicas profundas para o @professorisidro porém, seria legal falar do que você abre mão quando vai para o micriservices como, por exemplo, uma eventual consistência.
