### ISSUE TITLE
Cloud chapter

### ISSUE THREAD

**Issue by kmacedovarela** [otaviojava/manual-arquiteto-moderno#18]

**Comment by otaviojava** [comment]
> Caso queira ver na prática um excelente exemplo de como usufruir e implementar funcionalidades cloud-native, recomendo que você baixe e verifique o código da aplicação de exemplo gerada pelo site da especificação Microprofile.

Eu tenho medo de fechar com o MicroProfile, talvez seja legal falar também sobre o Spring, afinal, não tem como falar de Java e não mencionar Spring.

Um outro ponto é a relação entre cloud-native e MicroProfile, em tese MicroProfile é para Microservices. Consigo dizer que todo aplicativo em microservices implementa cloud?

**Comment by eldermoraes** [comment]
Ao dizer "Spring" você quer dizer "Spring Boot", né?

Porque implentar microservices com Spring é como fazer o mesmo com Jakarta EE. Dá pra fazer, mas...

**Comment by otaviojava** [comment]
Boa @eldermoraes sim, quero dizer que seria legal mostrar todos os lados da moeda.

**Comment by otaviojava** [comment]
> Utilização da plataforma Kubernetes: em caso de IaaS ou PaaS:

Esse é um ponto bem polêmico, pq, geralmente, quando definimos tipo de serviçso falamos de um ponto de vista da organização e não apenas de uma pessoa ou um grupo de pessoas dentro da organização. É tipo: Minha empresa precisa ou não manter? 
Dizer que o Kubernetes é PaaS pq traz um ponto de vista do dev é um caminho sem volta. Afinal, posso falar que Java é SaaS no ponto de vista do usuário. Afinal, ele não precisa lidar com nada.

**Comment by otaviojava** [comment]
O tópico "Kubernetes - Quando usar e quando não usar" acaba não falando quando não utilizar, talvez trocar o tópico para "boas práticas e/ou vantagens no uso do Kubernetes"

**Comment by sergiolopessp** [comment]
Gostei muito

**Comment by kmacedovarela** [comment]
Obrigada @sergiolopessp 

@otaviojava, @eldermoraes , itens endereçados. Obrigada pelo feedback.

https://github.com/otaviojava/manual-arquiteto-moderno/commit/403097cc0a5d95fb69a4ee7a4a94e13440daa893
