### ISSUE TITLE
Preencher o about me.

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/manual-arquiteto-moderno#2]
Colocar como currículo dentro do arquivo aboutme.

- [x] Otavio Santana
- [x] Sergio
- [x] Karina
- [x] Elder
- [x] Sandro
- [x] Isidro 
- [x] Salaboy
- [ ] Rafael Pontes
- [ ] Leandro Domingues

**Comment by kmacedovarela** [comment]
@salaboy @rponte @sergiolopessp @sandrogiacom @professorisidro @jhomarolo @eldermoraes Please remember to add you on the about-me section

**Comment by salaboy** [comment]
@kmacedovarela done here: https://github.com/otaviojava/manual-arquiteto-moderno/pull/30/

**Comment by professorisidro** [comment]
@kmacedovarela @otaviojava done!
