### ISSUE TITLE
Reorder chapters

### ISSUE THREAD

**Issue by kmacedovarela** [otaviojava/manual-arquiteto-moderno#22]
I was speaking to @Salaboy and we think we should put the DDD chapter after the cloud chapter. It will have a practical example that will link concepts and patterns presented on microservices and cloud, to DDD practice. 

WDYT? @otaviojava @sergiolopessp

**Comment by kmacedovarela** [comment]
8 A importância de aprender os conceitos ao invés de novos frameworks
1 Domain Driven Design (DDD), where to go next?
2 Clean Code
3 Clean Architecture
4 Refatoração
6 Banco de dados
5 Microservices
7 Cloud
9 Precisamos falar sobre atualizações
10 Destrinchando performance de aplicações

**Comment by otaviojava** [comment]
@kmacedovarela https://github.com/otaviojava/manual-arquiteto-moderno/pull/45
