### ISSUE TITLE
Atualizar a bibliografia com os livros base

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/manual-arquiteto-moderno#3]
Como já conversamos seria muito importante falar um pouco sobre os livros que definimos como mínimo para a leitura desse manual.

Até o momento temos esses: 

* Java Efetivo;
* Clean Code;
* DDD;
* Clean Architecture;
* Building Microservices;
* The Twelve Factors;

**Comment by kmacedovarela** [comment]
Acabei de colocar na lista os livros que usei no capitulo de cloud; 
https://github.com/otaviojava/manual-arquiteto-moderno/commit/8da5c3ba422795b0dc5902aabb36e3f00cc37797

**Comment by kmacedovarela** [comment]
@salaboy @eldermoraes @sergiolopessp 
Please remember to add to bibliography.md any books you might have mentioned or used as inspiration
