### ISSUE TITLE
Renomear imagens de acordo com os capítulos que foram renomeados

### ISSUE THREAD

**Issue by kmacedovarela** [otaviojava/manual-arquiteto-moderno#47]

**Comment by afonsoaugusto** [comment]
Opa, dei uma olhada aqui e as imagens já estão com o número e a posição do capítulo que ela é invocada.
A issue seria para isso mesmo, ou seria para colocar o nome por extenso do capítulo onde é importada?

**Comment by kmacedovarela** [comment]
Opa, a issue era justamente pra isso @afonsoaugusto . Obrigada por verificar. Com a sua confirmação podemos fechar esta issue.
