### ISSUE TITLE
Escrever sobre o clean code

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/manual-arquiteto-moderno#5]
- [x] Dando adeus ao excesso de getters e setters
- [x] SOLID na prática
- [x] Lombok: problema ou solução?
- [x] Definindo APIs a prova de bala

**Comment by sergiolopessp** [comment]
@otaviojava para mim está ok, acho que você cobriu os pontos que você marcou

**Comment by otaviojava** [comment]
@sergiolopessp value se tiver algum ponto que eu deveria cobrir pode falar também, blz?

**Comment by sergiolopessp** [comment]
@otaviojava será que faz sentido explicar o significado de cada parte do SOLID, ou por estarmos falando de plenos e senior, já devemos considerar que eles sabem o que é SOLID?

**Comment by otaviojava** [comment]
Sim, esse é um ponto mínimo.
IMHO fazer o SOLID está na parte que eu defino de conhecimento mínimo.
Acho legal colocar como referência na bibliografia.

**Comment by antoniolazaro** [comment]
Sugestão seria colocar referência sobre SOLID, KISS, GOF. ou como pré-requisito
