### ISSUE TITLE
Escrever sobre Microservices

### ISSUE THREAD

**Issue by otaviojava** [otaviojava/manual-arquiteto-moderno#8]
* Pontos de atenção
* Vantagens e desvantagens em relação ao monolito
* Planejando uma migração de um monolito para uma arquitetura de microservices
* Teorema do CAP e seus impactos na arquitetura
* DTO ou não DTO?
* Melhores práticas para se definir camadas da aplicação
* Segurança
	* BASIC
	* Auth
	* Auth 2
* Paginação

**Comment by otaviojava** [comment]
@sergiolopessp eu movi o seu matérial para o Markdonw

https://github.com/otaviojava/manual-arquiteto-moderno/blob/master/chapter_04.md

**Comment by otaviojava** [comment]
@sergiolopessp uma pergunta:

:question: 
Eu já tenho um material que fala sobre segurança, existe algum problema de eu abrir um PR sobre esse assunto para vc complementar?

**Comment by otaviojava** [comment]
Eu coloquei um material que eu tenho sobre DTO, veja se ele é útil de alguma forma.

**Comment by otaviojava** [comment]
Outra coisa, seria legal escrever sobre Paginação.

**Comment by sergiolopessp** [comment]
@otaviojava  acho legal vc mandar esse material de segurança e a gente vai complementando.

**Comment by sergiolopessp** [comment]
@otaviojava fiquei na dúvida se paginação entraria mais em banco de dados, porque é estratégia de banco.
Mudei também os tópicos um pouco, para algo que começou a fazer mais sentido na hora que estou escrevendo.

**Comment by sergiolopessp** [comment]
@otaviojava complementei com as informações sobre os tipos de monolitos. Valeu pela dica
